# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 06:08
from __future__ import unicode_literals

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='WEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('docfile', models.FileField(upload_to='uploads/%Y/%m/%d', validators=[content.models.WEvent.validate_file_extension])),
            ],
        ),
    ]
